NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently.

## 1. Introduction to NumPy

To use NumPy, you first need to import it. By convention, NumPy is imported with the alias np.

In [1]:
import numpy as np

## 2. Arrays

The central feature of NumPy is the ndarray, a homogeneous n-dimensional array object.

### i. Creating Arrays

#### From a list

In [2]:
# Creating a 1D array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr) 
print('\n')

# Creating a 2D array from a list of lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]


[[1 2 3]
 [4 5 6]]


#### Using built-in functions

In [3]:
# Creating an array of zeros
zeros = np.zeros((2, 3))
print(zeros)
print('\n')

# Creating an array of ones
ones = np.ones((3, 2))
print(ones)
print('\n')

# Creating an array with a range of values
range_array = np.arange(0, 10, 2)
print(range_array)
print('\n')

# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
print(linspace_array) 

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


[0 2 4 6 8]


[0.   0.25 0.5  0.75 1.  ]


## 3. Array Attributes 

### Common attributes of arrays

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape of the array
print(arr.shape)
print('\n')

# Number of dimensions
print(arr.ndim)
print('\n')

# Size (total number of elements)
print(arr.size)  
print('\n')

# Data type of the elements
print(arr.dtype)

(2, 3)


2


6


int64


## 4. Array Indexing and Slicing

### Indexing

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  
print(arr[-1])
print('\n')

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[0, 1])  # Output: 2 (element at first row, second column)


10
50


2


### Slicing

In [6]:
# 1D array slicing
print(arr[1:4])
print('\n')

# 2D array slicing
print(arr_2d[:, 1])  # (second column of all rows)
print(arr_2d[1, :])  # (all columns of second row)

[20 30 40]


[2 5]
[4 5 6]


## 5. Array Operations

### Arithmetic operations

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print(arr1 + arr2)
print('\n')

# Element-wise multiplication
print(arr1 * arr2)  
print('\n')

# Element-wise subtraction
print(arr1 - arr2)  
print('\n')

# Element-wise division
print(arr1 / arr2)  

[5 7 9]


[ 4 10 18]


[-3 -3 -3]


[0.25 0.4  0.5 ]


### Universal functions (ufuncs)

In [8]:
# Square root
print(np.sqrt(arr1)) 
print('\n')

# Exponential
print(np.exp(arr1))  
print('\n')

# Sine
print(np.sin(arr1)) 

[1.         1.41421356 1.73205081]


[ 2.71828183  7.3890561  20.08553692]


[0.84147098 0.90929743 0.14112001]


## 6. Array Manipulation

### Reshaping

In [9]:
arr = np.arange(1, 7)
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


### Flattening

In [10]:
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)  

[1 2 3 4 5 6]


### Concatenation

In [11]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenating arrays along rows (axis 0)
concat_arr = np.concatenate((arr1, arr2), axis=0)
print(concat_arr)
print('\n')

# Concatenating arrays along columns (axis 1)
arr3 = np.array([[7], [8]])
concat_arr = np.concatenate((arr1, arr3), axis=1)
print(concat_arr)

[[1 2]
 [3 4]
 [5 6]]


[[1 2 7]
 [3 4 8]]


## 7. Statistical Operations

### Basic statistical functions

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum
print(np.sum(arr))
print('\n')

# Mean
print(np.mean(arr))  
print('\n')

# Standard deviation
print(np.std(arr))  
print('\n')

# Minimum
print(np.min(arr))  
print('\n')

# Maximum
print(np.max(arr))  
print('\n')

# Sum along an axis
print(np.sum(arr, axis=0))  # (sum of each column)
print(np.sum(arr, axis=1))  # (sum of each row)


21


3.5


1.707825127659933


1


6


[5 7 9]
[ 6 15]


## 8. Linear Algebra

### Dot product

In [13]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(arr1, arr2)
print(dot_product)

[[19 22]
 [43 50]]


### Matrix multiplication

In [14]:
matrix_product = np.matmul(arr1, arr2)
print(matrix_product)

[[19 22]
 [43 50]]


### Determinant

In [15]:
det = np.linalg.det(arr1)
print(det) 

-2.0000000000000004


### Inverse

In [16]:
inv = np.linalg.inv(arr1)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


## 9. Random Module

NumPy also includes a random module for generating random numbers and performing random operations.

In [17]:
# Generating a random array
random_arr = np.random.rand(3, 2)
print(random_arr)
print('\n')

# Generating random integers
random_int_arr = np.random.randint(0, 10, (3, 3))
print(random_int_arr)

[[0.87542702 0.65221273]
 [0.13105851 0.37571866]
 [0.13266352 0.68976846]]


[[2 4 4]
 [6 4 0]
 [0 4 2]]


## 10. Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

# Broadcasting arr1 to match the shape of arr2
result = arr1 + arr2
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
